name: build-converter-workflow

on: workflow_dispatch

jobs:
  build:
    name: Build the image
    runs-on: ubuntu-22.04
    steps:

      - name: "Check out repo"
        uses: actions/checkout@v4

      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: "Build Docker image"
        run: |
          docker build . -f containers/Dockerfile \

            -t ghcr.io/edinburgh-genome-foundry/sequeduct_methyl:v0.1.2 \
            -t ghcr.io/edinburgh-genome-foundry/sequeduct_methyl:latest

      - name: "Release Docker image"
        run: |
          docker push ghcr.io/edinburgh-genome-foundry/sequeduct_methyl:v0.1.2
          docker push ghcr.io/edinburgh-genome-foundry/sequeduct_methyl:latest